spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:15432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create